# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46727abd36fb6b04ab07017eab03076e918c2244820daa97f24db4d60cd0f6f63a5984082d02bfd8433f915dc5d032a6eaa48c1aa4bf005abd146bfa29425004

test:
  secret_key_base: 890d3ef117d2022ae1b02197606010a4826afb0663acc40b8640a412ec6c1d1a2b902e7d397067b94536adb2d197c9f482440f609849e97704ea60be4fbfe017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
